/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.melkeinsuorakaide;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 20128509
 */
public class frmSuorakaide extends javax.swing.JFrame {

    /**
     * Creates new form frmSuorakaide
     */
    public frmSuorakaide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblAlkutervehdys = new javax.swing.JLabel();
        jlblLeveys = new javax.swing.JLabel();
        jlblKorkeus = new javax.swing.JLabel();
        jtxtLeveys = new javax.swing.JTextField();
        jtxtKorkeus = new javax.swing.JTextField();
        jbtnLaske = new javax.swing.JButton();
        jtxtPintaala = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlblLeveysvirhe = new javax.swing.JLabel();
        jlblKorkeusvirhe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblAlkutervehdys.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblAlkutervehdys.setText("Anna suorakaiteen leveys ja korkeus, lasken pinta-alan.");

        jlblLeveys.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblLeveys.setText("Leveys (m):");

        jlblKorkeus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblKorkeus.setText("Korkeus (m):");

        jtxtLeveys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLeveysActionPerformed(evt);
            }
        });

        jtxtKorkeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtKorkeusActionPerformed(evt);
            }
        });

        jbtnLaske.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jbtnLaske.setText("Laske pinta-ala");
        jbtnLaske.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtnLaskeFocusLost(evt);
            }
        });
        jbtnLaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLaskeActionPerformed(evt);
            }
        });

        jtxtPintaala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPintaalaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Pinta-ala (m2):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jlblAlkutervehdys))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jlblKorkeus)
                            .addComponent(jlblLeveys)
                            .addComponent(jtxtKorkeus)
                            .addComponent(jbtnLaske, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtLeveys)
                            .addComponent(jtxtPintaala))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblLeveysvirhe, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(jlblKorkeusvirhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlblAlkutervehdys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jlblLeveys)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblLeveysvirhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtLeveys))
                .addGap(18, 18, 18)
                .addComponent(jlblKorkeus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtKorkeus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblKorkeusvirhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jbtnLaske)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtPintaala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLaskeActionPerformed
        // Ohjelman tarvitsemat muuttujat
        float leveys, korkeus, pintaala;
        
        // Haetaan ja muunnetaan käyttöliittymästä arvot
        /*
        try {
        //  Block of code to try
        }
        catch(Exception e) {
        //  Block of code to handle errors
        }
        
        String etunimi="Katariina", sukunimi="Bia", kokonimi;
        kokonimi = etunimi + " " + sukunimi + "hun";
        ==> kokonimi on siis Katariina Biahun
        
        */
        
        try {
            leveys = Float.parseFloat(jtxtLeveys.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. Korjaa jälkesi. virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
        
        // jos leveys on pinempi tai yhtäsuuri kuin nolla, niin...
        if (leveys<=0) {
            // retrnilla ohjelman ajo tässä metodissa lopuu ja palataan pääohjelmaan
            jlblLeveysvirhe.setForeground(Color.red);
            jlblLeveysvirhe.setText("Leveys täytyy olla suurempi tai yhtäsuuri kuin nolla.");
            return;
        } else {
            // ei ollut virheitä, tyhjennetään virhekenttä laitamalla kaksi lainausmerkkiä parametriksi
            jlblLeveysvirhe.setText("");
        }
    
        try {
            korkeus = Float.parseFloat(jtxtKorkeus.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. Korjaa jälkesi. virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
        
        // jos korkeus on pinempi tai yhtäsuuri kuin nolla, niin...
        if (korkeus<=0) {
            // retrnilla ohjelman ajo tässä metodissa lopuu ja palataan pääohjelmaan
            jlblKorkeusvirhe.setForeground(Color.red);
            jlblKorkeusvirhe.setText("Korkeus täytyy olla suurempi tai yhtäsuuri kuin nolla.");
            return;
        } else {
            // ei ollut virheitä, tyhjennetään virhekenttä laitamalla kaksi lainausmerkkiä parametriksi
            jlblKorkeusvirhe.setText("");
        }
        
        // Lasketaan pinta-ala
        pintaala = leveys*korkeus;
        
        // Muunnetaan pinta-ala float -- string-tyyppiseksi
        jtxtPintaala.setText(String.valueOf(pintaala));
       
    }//GEN-LAST:event_jbtnLaskeActionPerformed

    private void jtxtKorkeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtKorkeusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtKorkeusActionPerformed

    private void jbtnLaskeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtnLaskeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLaskeFocusLost

    private void jtxtPintaalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPintaalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPintaalaActionPerformed

    private void jtxtLeveysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLeveysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLeveysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSuorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSuorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSuorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSuorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSuorakaide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnLaske;
    private javax.swing.JLabel jlblAlkutervehdys;
    private javax.swing.JLabel jlblKorkeus;
    private javax.swing.JLabel jlblKorkeusvirhe;
    private javax.swing.JLabel jlblLeveys;
    private javax.swing.JLabel jlblLeveysvirhe;
    private javax.swing.JTextField jtxtKorkeus;
    private javax.swing.JTextField jtxtLeveys;
    private javax.swing.JTextField jtxtPintaala;
    // End of variables declaration//GEN-END:variables
}
